In [1]:
import numpy as np
import pandas as pd

### Loading file

In [2]:
df = pd.concat(pd.read_excel("D:/Data Science/imus.xlsx",sheet_name = None), ignore_index=True)

In [3]:
#data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2627926 entries, 0 to 2627925
Data columns (total 10 columns):
 #   Column           Dtype
---  ------           -----
 0   category         int64
 1   manufacturer     object
 2   part_number      object
 3   sku              object
 4   alt_sku          object
 5   description      object
 6   status           object
 7   qty              int64
 8   price            float64
 9   sku_create_date  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 200.5+ MB

In [4]:
#checking unique values in dataset
df.nunique()

category              153
manufacturer         1484
part_number        334574
sku                379112
alt_sku              2079
description        339222
status                  2
qty                  2618
price              122688
sku_create_date        10
dtype: int64

In [5]:
df.shape

(2627926, 10)

In [6]:
#Checking for null values
df.isnull().sum()

category                 0
manufacturer             0
part_number              0
sku                      0
alt_sku            2613442
description              0
status                   0
qty                      0
price                    0
sku_create_date          0
dtype: int64

In [7]:
#Percentage error of alt_sku
print((df['alt_sku'].isnull().sum()/len(df['alt_sku']))*100)

99.448842927845

In [8]:
#Dropping the alt_sku
df = df.drop(columns = ['alt_sku'])

In [9]:
df.nunique()

category              153
manufacturer         1484
part_number        334574
sku                379112
description        339222
status                  2
qty                  2618
price              122688
sku_create_date        10
dtype: int64

In [10]:
#Checking for duplicates
duplicates = df[df.duplicated()]
duplicates.head(10)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date
70,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
71,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
72,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
73,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
74,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
75,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
76,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
77,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
78,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17
79,1022,FELLOWES,52045,BA5888,"100PK LAMINATING POUCHES LEGAL, 5MIL",No Stock,0,44.75,2020-08-17

In [11]:
#droping the dublicates
df.drop_duplicates(inplace=True)
df.head()

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17

In [12]:
df.shape

(1105970, 9)

For data In Stock:

Which are the top Manufacturers with price, quantity?

Which are the most profitable products?

Which is the product where you have seen a decrease in the price?

Which is the product where you have seen an increase in the price?

Which is the top category by price and quantity?

Which products are aging?

How to Decrease Product aging?

In [13]:
#Dividing the data in instock and no stock
indf = df[df['status']=='In Stock']
outdf = df[df['status']=='No Stock']

In [14]:
print(f'Shape of Instock : {indf.shape}')
print(f'Shape of OutStock : {outdf.shape}')

Shape of Instock : (156814, 9)
Shape of OutStock : (949156, 9)

In [15]:
#top manufacturers with quantity
print("The Top 10 manufacturers based on quantity produced are :")
indf.groupby(['manufacturer'],as_index=False)['qty'].sum().sort_values('qty',ascending=False).head(10)

The Top 10 manufacturers based on quantity produced are :

                        manufacturer       qty
181      DELL CSG SERVICE WARRANTIES  13578833
147                         CONFIG 6   3825896
184              DELL ESG WARRANTIES   3149689
620                     STARTECH.COM   1884895
650          TRIPP LITE CONNECTIVITY   1590370
433  LOGITECH - COMPUTER ACCESSORIES    972244
515                  PLANTRONICS INC    957135
290    HP INC. - SB DESKTOP DISPLAYS    905072
709                    WASP -PROJECT    689931
79                   BELKIN - CABLES    578216

In [16]:
##top manufacturers with price
print("The Top 10 manufacturers who sell products that have highest price are :")
indf.groupby(['manufacturer'],as_index=False)['price'].max().sort_values('price',ascending=False).head(10)

The Top 10 manufacturers who sell products that have highest price are :

                 manufacturer     price
315           HPE - SWITCHING  69729.03
311          HPE - NIMBLE BTO  40893.99
303       HPE - ARUBA INSTANT  35554.13
529              PULSE SECURE  23423.40
444     MELLANOX TECHNOLOGIES  20144.08
132           CISCO  HW VIDEO  17356.11
243       FLUKE NETWORKS CORE  16999.12
476          NETALLY HH TOOLS  15082.98
316         HPE - TOP OF RACK  14558.86
612  SONICWALL - NSA HARDWARE  13150.27

In [17]:
#Creating the new variable called Revenue
df['Revenu'] = df['qty'] * df['price']

In [18]:
df.tail(4)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,Revenu
2627895,2240,BELKIN - CABLES,A3X126-10-RED,972494,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.77,2020-08-28,7.54
2627903,2240,BELKIN - CABLES,A3X126-10-RED,972494,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.50,2020-08-28,7.00
2627912,9945,VERBATIM CORPORATION,93975,986034,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,51.88,2020-08-28,622.56
2627913,9945,VERBATIM CORPORATION,93975,986034,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28,606.36

In [19]:
indf=df[df["status"] == "No Stock"]
indf

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,Revenu
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17,0.0
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17,0.0
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17,0.0
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17,0.0
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17,0.0
...,...,...,...,...,...,...,...,...,...,...
2627418,3360,TARGUS,AMB580TT,9X4546,"B580 BLUETOOTH MOUSE BLCK,",No Stock,0,19.53,2020-08-28,0.0
2627775,505,ENGENIUS,EAP1300,9Z0170,"11AC WAVE 2 INDOOR WRLS AP,",No Stock,0,85.24,2020-08-28,0.0
2627822,9910,KINGSTON,HX-MPFS-SM,9Z6619,"HYPERX FURY S PRO GAMING, MOUSE PAD SMALL",No Stock,0,13.75,2020-08-28,0.0
2627853,291,KINGSTON TECHNOLOGY FLASH,SD10VG2/16GBCP,9Z8507,"BULK 16GB SDHC CLASS 10 UHS-I, 45R MUST ORDER ...",No Stock,0,16.51,2020-08-28,0.0
2627857,291,KINGSTON,IKD300S/4GB,9103LA,"4GB D300S/D300SM AES 256 XTS, ENCRYPTED USB DRIVE",No Stock,0,52.83,2020-08-28,0.0

In [20]:
#Assuming that the profitable products are the ones that generate maximum revenue.
q2 = indf.groupby('description',as_index=False)['Revenu'].sum().sort_values(by='Revenu', ascending=False)
q2.head(10)

                                              description  Revenu
0                              #ESGE LOAD SOURCE SPECIFY,     0.0
210157  IND MEDIA CONV10/100/1000BASE-T, TO 1000BASE-S...     0.0
210164  IND THIN CLIENT15IN XGA TOUCH, PANEL PC ATOM E...     0.0
210163  IND THIN CLIENT 15IN XGA TPC, ATOM E3827 1.75G...     0.0
210162  IND THIN CLIENT 15IN XGA TOUCH, PANEL PC ATOM ...     0.0
210161  IND THIN CLIENT 15.6IN TOUCH, PANEL ATOM E3827...     0.0
210160  IND MNG ENET SWITCH 4, 10/100MBPS POE+ 2 GE SF...     0.0
210159  IND MNG ENET SWITCH 4 10/100, POE+ 2 100MBPS S...     0.0
210158  IND MINI CONVERTER 10/100BTX, TO 100BFX SC SM ...     0.0
210156  IND MEDIA CONV10/100/1000BASE-T, TO 100/1000BA...     0.0

In [21]:
indf = indf.sort_values("sku_create_date")
indf['price_diff'] = indf.groupby('description')['price'].diff().fillna(0)
indf.head(10)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,Revenu,price_diff
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17,0.0,0.00
667924,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,93.03,2020-08-17,0.0,0.00
667919,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,92.11,2020-08-17,0.0,-0.92
667918,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,94.85,2020-08-17,0.0,2.74
667910,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,101.23,2020-08-17,0.0,0.00
667905,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,100.23,2020-08-17,0.0,-1.00
667904,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,103.22,2020-08-17,0.0,2.99
667868,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,101.23,2020-08-17,0.0,0.00
667863,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,100.23,2020-08-17,0.0,-1.00
667862,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,103.22,2020-08-17,0.0,2.99

In [22]:
print("Top 10 products that show maximum decrease in price (Period=1)")
indf.sort_values('price_diff').head(10)

Top 10 products that show maximum decrease in price (Period=1)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,Revenu,price_diff
1653733,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEES3,ZA6701,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,909750.00,2020-08-24,0.0,-3566850.00
2348891,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEES3,ZA6701,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,909750.00,2020-08-25,0.0,-2729250.00
2348851,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LPHOME6M,ZA6661,"CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...",No Stock,0,1679538.60,2020-08-25,0.0,-2157547.75
2068605,1211,PLANAR DVLED,106621 INSTALL,5NU738,"DIRECTLIGHT 24X6, DL2 0.9 ROOM 250",No Stock,0,54649.05,2020-08-24,0.0,-1884383.25
1653603,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-24,0.0,-1783425.00
388521,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-17,0.0,-1783425.00
2348826,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-25,0.0,-1364625.00
426242,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC500ENT,1F6035,"SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...",No Stock,0,1376587.43,2020-08-17,0.0,-1070679.12
388570,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LPHOME6M,ZA6661,"CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...",No Stock,0,2066123.25,2020-08-17,0.0,-1053020.13
1777042,1241,VMWARE - FEDERAL,MCS-PLUS-3SUP-F,2NP781,"FED MC + ADDL MCS COVERAGE ALA, WRKSPCE1 PRODU...",No Stock,0,490386.81,2020-08-24,0.0,-980773.60

In [23]:
price_change= indf.groupby('description',as_index=False)['price_diff'].sum().sort_values(by='price_diff',ascending=False)

In [24]:
decrease = price_change[price_change['price_diff']<0]

In [25]:
print("Top 10 Products (L to H) on which reduction of price was maximum: ")
decrease.tail(10)

Top 10 Products (L to H) on which reduction of price was maximum:

                                              description  price_diff
153776  CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....  -418800.00
154265  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B AS...  -462473.23
238260     QUANTITY 150 OF EL4Q 387GB SFF, 2 4K SSD LINUX  -468467.99
154276  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B PR...  -483910.58
238292          QUANTITY 150 OF ES7E 775GB SFF, 2 SSD 5XX  -628213.02
154656  CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...  -717942.97
130147                           ANNESE ONLY 2018-380048,  -722188.74
238325                QUANTITY 150 OF ESGP 1 55TB SAS, 4K  -780127.17
238261     QUANTITY 150 OF EL4S 775GB SFF, 2 4K SSD LINUX  -809504.34
200357  FED MC + ADDL MCS COVERAGE ALA, WRKSPCE1 PRODU...  -980773.60

4 Answer

In [26]:
increase = price_change[price_change['price_diff']>0]

In [27]:
print("Top 10 Products on which increase in price was maximum: ")
increase.head(10)

Top 10 Products on which increase in price was maximum:

                                              description  price_diff
254151  SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...  2141358.23
186527                 DIRECTLIGHT 24X6, DL2 0.9 ROOM 250  1884383.25
254152  SCI MANAGED SVCS PROF SECURITY, MONITORING MNT...  1427572.15
238283  QUANTITY 150 OF ES0S 775GB SFF, 2 4K SSD AIX L...   961685.68
254153  SCI MANAGED SVCS STD SECURITY, MONITORING MNT ...   713786.08
182769               CTO COMPELLENT WARRANTY, EXP 6/30/19   562697.08
238281  QUANTITY 150 OF ES0Q 387GB SFF, 2 4K SSD AIX L...   556572.19
152880  CCW ONLY SWSS UPG 3YR DISTI BAC, 500 000 SUBSC...   243813.00
154277  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B PR...   195981.99
235633                    PROFESSIONAL SVCS BACKUP CLOUD,   189063.80

5 Answer

In [28]:
top_cat= indf.sort_values('price',ascending = False).reset_index() 
var = top_cat['category'][0]
{var}

{1231}

7 Answer
- First in First out

## Outstock data

1 Answer: Which are the top Manufacturers with price, quantity?

In [29]:
outdf[outdf['qty']>0]

Empty DataFrame
Columns: [category, manufacturer, part_number, sku, description, status, qty, price, sku_create_date]
Index: []

In [30]:
print("The Top 10 manufacturers based on price for out of stock products are :")
outdf.groupby(['manufacturer'],as_index=False)['price'].max().sort_values('price',ascending=False).head(10)

The Top 10 manufacturers based on price for out of stock products are :

                         manufacturer        price
57                             ALTNET  84974533.10
717              JUNIPER ROW SERVICES  10449000.00
709        JUNIPER ENTERPRISE ROUTING   5600000.00
231            CISCO - CCW MULTI YEAR   4700430.00
590       HPE - ENTERPRISE NETWORKING   4173518.27
636                     IGEL SOFTWARE   3609856.25
779         LENOVO DCG SERVER OPTIONS   3552553.59
1111  SECURE CHANNELS INC DIRECT SHIP   2447266.55
980                      PLANAR DVLED   1939032.30
596              HPE - SERVER OPTIONS   1627920.00

2 Answer: Which are the most profitable products?

In [31]:
qo2 = outdf.groupby('description',as_index=False)['price'].max().sort_values(by='price', ascending=False)
qo2.head(10)

                                              description        price
129283  ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...  84974533.10
129756  ALTNET TPM UP TO 80000000 USD, LIST MNT UPTO 8...  28324844.37
251188                  ROW 5YR SWA SUP FOR, JCE-1000GBPS  10449000.00
251184                  ROW 3YR SWA SUP FOR, JCE-1000GBPS   6966000.00
8598                 1000 UNIT BNDL OF, QSFP-100GBASE-LR4   5600000.00
154600  CCW ONLY SWSS UPG 3YR DISTI, SO=INTELL AUTOCLD...   4700430.00
153776  CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....   4476600.00
89099            3YR RH ANS TWR+ENG SY 10000N, 24X7 E-LTU   4173518.27
154656  CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...   3837086.35
312235      WORKSPACE ED LICS ELA W/, 1YR MNT 100000 LICS   3609856.25

3 Answer: Which is the product where you have seen a decrease in the price?

In [32]:
outdf = outdf.sort_values("sku_create_date")
outdf['price_diff'] = outdf.groupby('description')['price'].diff().fillna(0)
outdf.head(10)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,price_diff
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17,0.00
667924,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,93.03,2020-08-17,0.00
667919,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,92.11,2020-08-17,-0.92
667918,9920,KENSINGTON TECHNOLOGY GROUP,K67951US,3V1652,"CUSTOM WINDFALL FRAME IPAD, FOR IPAD AIR AIR 2...",No Stock,0,94.85,2020-08-17,2.74
667910,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,101.23,2020-08-17,0.00
667905,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,100.23,2020-08-17,-1.00
667904,9920,KENSINGTON TECHNOLOGY GROUP,K67949US,3V1651,"WINDFALL CONF ROOMS IPAD MINI, SUPPORTS ALL IP...",No Stock,0,103.22,2020-08-17,2.99
667868,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,101.23,2020-08-17,0.00
667863,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,100.23,2020-08-17,-1.00
667862,9920,KENSINGTON TECHNOLOGY GROUP,K67945US,3V1647,"WINDFALL FRAME SURFACE PRO 3/4,",No Stock,0,103.22,2020-08-17,2.99

In [33]:
outdf.sort_values('price_diff').head(10)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,price_diff
1653733,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEES3,ZA6701,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,909750.00,2020-08-24,-3566850.00
2348891,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEES3,ZA6701,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,909750.00,2020-08-25,-2729250.00
2348851,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LPHOME6M,ZA6661,"CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...",No Stock,0,1679538.60,2020-08-25,-2157547.75
2068605,1211,PLANAR DVLED,106621 INSTALL,5NU738,"DIRECTLIGHT 24X6, DL2 0.9 ROOM 250",No Stock,0,54649.05,2020-08-24,-1884383.25
1653603,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-24,-1783425.00
388521,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-17,-1783425.00
2348826,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPS3UK,ZA6636,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,454875.00,2020-08-25,-1364625.00
426242,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC500ENT,1F6035,"SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...",No Stock,0,1376587.43,2020-08-17,-1070679.12
388570,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LPHOME6M,ZA6661,"CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...",No Stock,0,2066123.25,2020-08-17,-1053020.13
1777042,1241,VMWARE - FEDERAL,MCS-PLUS-3SUP-F,2NP781,"FED MC + ADDL MCS COVERAGE ALA, WRKSPCE1 PRODU...",No Stock,0,490386.81,2020-08-24,-980773.60

In [34]:
change2 = outdf.groupby('description',as_index=False)['price_diff'].sum().sort_values(by='price_diff',ascending=False)

In [35]:
decrease = change2[change2['price_diff']<0]

In [36]:
print("Top 10 Products on which reduction of price was maximum: ")
decrease.tail(10)

Top 10 Products on which reduction of price was maximum:

                                              description  price_diff
153776  CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....  -418800.00
154265  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B AS...  -462473.23
238260     QUANTITY 150 OF EL4Q 387GB SFF, 2 4K SSD LINUX  -468467.99
154276  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B PR...  -483910.58
238292          QUANTITY 150 OF ES7E 775GB SFF, 2 SSD 5XX  -628213.02
154656  CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...  -717942.97
130147                           ANNESE ONLY 2018-380048,  -722188.74
238325                QUANTITY 150 OF ESGP 1 55TB SAS, 4K  -780127.17
238261     QUANTITY 150 OF EL4S 775GB SFF, 2 4K SSD LINUX  -809504.34
200357  FED MC + ADDL MCS COVERAGE ALA, WRKSPCE1 PRODU...  -980773.60

4 Answer: Which is the product where you have seen a increase in the price?

In [37]:
outdf.sort_values('price_diff',ascending=False).head(10)

,category,manufacturer,part_number,sku,description,status,qty,price,sku_create_date,price_diff
388652,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEEX3,ZA6702,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,4476600.00,2020-08-17,3566850.00
426245,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC1000EN,1F6038,"SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...",No Stock,0,2447266.55,2020-08-17,2141358.23
1691227,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC1000EN,1F6038,"SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...",No Stock,0,2447266.55,2020-08-24,2141358.23
2068604,317,PLANAR DVLED,106621 NETWORK COMM,5NU737,"DIRECTLIGHT 24X6, DL2 0.9 ROOM 250",No Stock,0,1939032.30,2020-08-24,1884383.25
804208,317,PLANAR DVLED,106621 NETWORK COMM,5NU737,"DIRECTLIGHT 24X6, DL2 0.9 ROOM 250",No Stock,0,1939032.30,2020-08-17,1884383.25
2348850,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LPHOME6S,ZA6660,"CCW ONLY SWSS UPG 3YR DISTI, TR-069 MGMT FOR 6...",No Stock,0,3119143.38,2020-08-25,1439604.78
1691226,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC1000PR,1F6037,"SCI MANAGED SVCS PROF SECURITY, MONITORING MNT...",No Stock,0,1631511.03,2020-08-24,1427572.15
426244,1231,SECURE CHANNELS INC DIRECT SHIP,SCSVCSMNGEDSEC1000PR,1F6037,"SCI MANAGED SVCS PROF SECURITY, MONITORING MNT...",No Stock,0,1631511.03,2020-08-17,1427572.15
2348892,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LTCAEEX3,ZA6702,"CCW ONLY SWSS UPG 3YR DISTI SO=, CSC IA CLD 3....",No Stock,0,3639000.00,2020-08-25,1400700.00
1653605,1221,CISCO - CCW MULTI YEAR,CON-3ECMU-LNCPX3UK,ZA6637,"CCW ONLY SWSS UPG 3YR DISTI SO=, CLOUD PORTAL",No Stock,0,1819500.00,2020-08-24,1259925.00

In [38]:
increase = change2[change2['price_diff']>0]

In [39]:
print("Top 10 Products on which increase in price was maximum: ")
increase.head(10)

Top 10 Products on which increase in price was maximum:

                                              description  price_diff
254151  SCI MANAGED SVCS ENTERPRISE, SECURITY MONITORI...  2141358.23
186527                 DIRECTLIGHT 24X6, DL2 0.9 ROOM 250  1884383.25
254152  SCI MANAGED SVCS PROF SECURITY, MONITORING MNT...  1427572.15
238283  QUANTITY 150 OF ES0S 775GB SFF, 2 4K SSD AIX L...   961685.68
254153  SCI MANAGED SVCS STD SECURITY, MONITORING MNT ...   713786.08
182769               CTO COMPELLENT WARRANTY, EXP 6/30/19   562697.08
238281  QUANTITY 150 OF ES0Q 387GB SFF, 2 4K SSD AIX L...   556572.19
152880  CCW ONLY SWSS UPG 3YR DISTI BAC, 500 000 SUBSC...   243813.00
154277  CCW ONLY SWSS UPG 3YR DISTI, PRIME COLLAB-B PR...   195981.99
235633                    PROFESSIONAL SVCS BACKUP CLOUD,   189063.80

5 Answer: Which is the top category by price and quantity?

In [40]:
x = outdf.sort_values('price',ascending = False).reset_index() 
var = x['category'][0]

In [41]:
print(f' The Top Category by price is {var}')

 The Top Category by price is 1231